"""
Django settings for sharpdata project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sys
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
import json

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5afn*#@n%dz*6fy=b1wovyh)vz6%myqxot+o1erf0fjwwr8f@='

# SECURITY WARNING: don't run with debug turned on in production!
try:
    f = open("/var/www/config", "r")
    data = json.loads(f.read())
    f.close()
    STAGE = data.get('STAGE', 'dev')
    SQL_PASS = data.get('SQL_PASS', None)
    SQL_USER = data.get('SQL_USER', None)
except Exception as e:
    print(e)
    STAGE = "local"

if not os.environ.get('chargebee_key', 'test_V6NDtssBXfbAL2X4kJcX4LFwxcu7HAdZB'):
    raise Exception('chargebee key not found')

print("Setting stage : ", STAGE)
if STAGE == "prod":
    print("Stage is Prod")
    DEBUG = False
    trace_rate = 0.5
    sentry_sdk.init(
        dsn="https://c478f8a9d14e487ca3a28b2ff1711e6a@o462943.ingest.sentry.io/5473762",
        integrations=[DjangoIntegration()],
        traces_sample_rate=trace_rate,

        # If you wish to associate users to errors (assuming you are using
        # django.contrib.auth) you may enable sending PII data.
        environment=STAGE
    )
else:
    print("Stage is Dev!")
    DEBUG = True

healt_ips = []
for i in range(256):
    for j in range(256):
        healt_ips.append('172.31.{}.{}'.format(i, j))
ALLOWED_HOSTS = ['datahelp.io',
                 'sandbox.datahelp.io',
                 'datalabz.re',
                 'sandbox.datalabz.re',
                 '127.0.0.1',
                 '44.227.212.112',
                 '35.165.156.17',
                 'localhost',
                 'front-end-dev-1554902407.us-west-2.elb.amazonaws.com', '*'
                 ] + healt_ips

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'corsheaders',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'stripe',
    'payments',
    'payments_v2',
    'chat_widget',
    'interface_v2_forms'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sharpdata.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sharpdata.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

if STAGE == 'prod':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'django',
            'USER': SQL_USER,
            'PASSWORD': SQL_PASS,
            'PORT': '3306',
            'HOST': "prod-website-sql.crbhofyvowta.us-west-2.rds.amazonaws.com"
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Payment Gateway Keys

STRIPE_SECRET_KEY = 'sk_test_AnBK3DZm9kMIxPeAu12TKwVa00xXGiSjdg'
STRIPE_PUBLISHABLE_KEY = 'pk_test_GNAHG4B8jwWuaWUeUHrwnC2Y00jym8LeZG'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

if len(sys.argv) > 1:
    if sys.argv[1] == 'runserver':
        STATICFILES_FINDERS = [
            "django.contrib.staticfiles.finders.FileSystemFinder",
            "django.contrib.staticfiles.finders.AppDirectoriesFinder",
        ]
        PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        BASE_DIR = os.path.dirname(PROJECT_DIR)
        STATICFILES_DIRS = [                # For static files not particular to any app.
            os.path.join(PROJECT_DIR, "static"),
        ]

        STATIC_ROOT = os.path.join(BASE_DIR, "static")
        STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
X_FRAME_OPTIONS = 'ALLOWALL'
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
# CSRF_TRUSTED_ORIGINS = ['https://sandbox.datalabz.re', 'https://test.datalabz.re', 'https://datalabz.re']

# CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
if STAGE == "prod":
    CSRF_TRUSTED_ORIGINS = CORS_ORIGIN_WHITELIST = ['https://datalabz.re', 'https://app.datalabz.re', 'https://api.datalabz.re']
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    ALLOWED_HOSTS += [".datalabz.re"]
    SESSION_COOKIE_DOMAIN = ".datalabz.re"
elif STAGE == "test":
    CSRF_TRUSTED_ORIGINS = CORS_ORIGIN_WHITELIST = ['https://test.datalabz.re']
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    ALLOWED_HOSTS += [".test.datalabz.re"]
    SESSION_COOKIE_DOMAIN = ".test.datalabz.re"
elif STAGE == "dev":
    print("RUNGING IN DEV#####!")
    CSRF_TRUSTED_ORIGINS = CORS_ORIGIN_WHITELIST = ['https://sandbox.datalabz.re', "https://api.sandbox.datalabz.re",
                                                    "https://app.sandbox.datalabz.re"]
    ALLOWED_HOSTS += [".sandbox.datalabz.re"]
    SESSION_COOKIE_DOMAIN = ".sandbox.datalabz.re"
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

elif STAGE == "local":
    print("RUNNING IN LOCAL######!")
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    CSRF_TRUSTED_ORIGINS = CORS_ORIGIN_WHITELIST = ['http://localhost:3000', 'http://localhost:4000', 'http://127.0.0.1:3000']
