
p = {
    # PLANS
    "FUB_EMBEDDED_APP": "fub-embedded-app-v2",
    "FUB_ONLY_FUB_WEBFORM_PLUS": "fub-webform-pipeline-plus-v2",
    "FUB_ONLY_FUB_WEBFORM_MAX": "fub-webform-pipeline-max-v2",
    "FUB_SISU_FUB_WEBFORM_PLUS": "fub-sisu-wfp-plus-v2",
    "FUB_SISU_FUB_WEBFORM_MAX": "fub-sisu-wfp-max-v2",
    "FUB_SISU_OTC_FUB_WEBFORM_PLUS": "fub-sisu-otc-wfp-plus-v2",
    "FUB_SISU_OTC_FUB_WEBFORM_MAX": "fub-sisu-otc-wfp-max-v2",
    "FUB_OTC_FUB_WEBFORM_PLUS": "fub-otc-wfp-plus-v2",
    "FUB_OTC_FUB_WEBFORM_MAX": "fub-otc-wfp-max-v2",
    "OTC_WEBFORM_PLUS": "otc-webform-pipeline-plus-v2",
    "OTC_WEBFORM_MAX": "otc-webform-pipeline-max-v2",
    "CHAT_GPT_BETA": "chat-gpt-beta",
    "AUTOMATION_BUILDER_PLUS": "automation-builder-yearly",
    "AUTOMATION_BUILDER_MAX": "automation-builder-max-yearly",
    "WEBFORM_PLUS": "webform-plus-yearly",
    "WEBFORM_MAX": "webform-max-yearly",


    # ADDONS
    "ADDON_APP_DESC_MAX": {"id": "appt-desc-template-max-v2", "setup_fee": None},
    "ADDON_APP_DESC_PLUS": {"id": "appt-desc-template-plus-v2", "setup_fee": None},
    "ADDON_ASSIGNMENT_FORM": {"id": "assignment-form-v2", "setup_fee": None},
    "ADDON_CUSTOM_THEME": {"id": "custom-branded-themes-v2", "setup_fee": None},
    "ADDON_CUSTOM_THANKS": {"id": "custom-thank-you-msg-v2", "setup_fee": None},
    "ADDON_DISPOSITION_TEXT": {"id": "disposition-text-v2", "setup_fee": None},
    "ADDON_DOCUMENT_UPLOAD": {"id": "document-upload-v2", "setup_fee": None},
    "ADDON_OTC_BIDIRECTIONAL_MAX": {"id": "fub-otc-bi-sync-max-v2", "setup_fee": "sf-otc-bi-sync-v2"},
    "ADDON_OTC_BIDIRECTIONAL_PLUS": {"id": "fub-otc-bi-sync-plus-v2", "setup_fee": "sf-otc-bi-sync-v2"},
    "ADDON_FUB_OTC_INT_MAX": {"id": "fub-otc-integration-max-v2", "setup_fee": "sf-otc-inte-max-v2"},
    "ADDON_FUB_OTC_INT_PLUS": {"id": "fub-otc-integration-plus-v2", "setup_fee": "sf-otc-inte-plus-v2"},
    "ADDON_FUB_SISU_OTC_MAX": {"id": "fub-sisu-otc-inte-max-v2", "setup_fee": "sf-fub-sisu-otc-max-v2"},
    "ADDON_FUB_SISU_OTC_PLUS": {"id": "fub-sisu-otc-inte-plus-v2", "setup_fee": "sf-fub-sisu-otc-plus-v2"},
    "ADDON_SISU_BIDIRECTIONAL_MAX": {"id": "fub-sisu-bi-sync-max-v2", "setup_fee": "sf-sisu-bi-sync-v2"},
    "ADDON_SISU_BIDIRECTIONAL_PLUS": {"id": "fub-sisu-bi-sync-plus-v2", "setup_fee": "sf-sisu-bi-sync-v2"},
    "ADDON_FUB_SISU_INTE_MAX": {"id": "fub-sisu-integration-max-v2", "setup_fee": "sf-sisu-inte-max-v2"},
    "ADDON_FUB_SISU_INTE_PLUS": {"id": "fub-sisu-integration-plus-v2", "setup_fee": "sf-sisu-inte-plus-v2"},
    "ADDON_OPTIONAL_AUTOMATION_MAX": {"id": "optional-automation-max-v2", "setup_fee": "sf-optional-automation-v2"},
    "ADDON_OPTIONAL_AUTOMATION_PLUS": {"id": "optional-automation-plus-v2", "setup_fee": "sf-optional-automation-v2"},
    "ADDON_OPTIONAL_FILED_MAX": {"id": "optional-fields-max-v2", "setup_fee": "sf-sisu-optional-fields-v2"},
    "ADDON_OPTIONAL_FILED_PLUS": {"id": "optional-fields-plus-v2", "setup_fee": "sf-sisu-optional-fields-v2"},
    "ADDON_OTC_OPTIONAL_FILED_MAX": {"id": "otc-optional-fields-max-v2", "setup_fee": "sf-otc-optional-fields-v2"},
    "ADDON_OTC_OPTIONAL_FILED_PLUS": {"id": "otc-optional-fields-plus-v2", "setup_fee": "sf-otc-optional-fields-v2"},
    "ADDON_OTC_CUSTOM_FIELDS_MAX": {"id": "otc-custom-fields-max-v2", "setup_fee": "sf-otc-custom-fields-v2"},
    "ADDON_OTC_CUSTOM_FIELDS_PLUS": {"id": "otc-custom-fields-plus-v2", "setup_fee": "sf-otc-custom-fields-v2"},
    "ADDON_SISU_CUSTOM_FIELDS_MAX": {"id": "sisu-custom-fields-max-v2", "setup_fee": "sf-sisu-custom-fields-v2"},
    "ADDON_SISU_CUSTOM_FIELDS_PLUS": {"id": "sisu-custom-fields-plus-v2", "setup_fee": "sf-sisu-custom-fields-v2"},
}
